apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: busy-pod-taint-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busy-pod-taint
  template:
    metadata:
      labels:
        app: busy-pod-taint
    spec:
      containers:
      - image: busybox
        name: busy-pod-taint
        resources: {}
        command: 
        - sleep
        - "5000"
