apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: secondapp
  name: secondapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secondapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: secondapp
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
