apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypodvolume
  volumes:
    - name: mypodvolume
      persistentVolumeClaim:
        claimName: fast-pvc
