apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: peoples.marek.com
  finalizers:
  - something.here.com
spec:
  scope: Cluster
  group: marek.com
  version: v1
  names:
    kind: People
    plural: peoples
    singular: people
    shortNames:
    - peo
validation:
  openAPIV3Schema:
    properties:
      spec:
        properties:
          firstName:
            type: integer
            minimum: 50
            maximum: 250

