apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: marek-pods-role
  namespace: default
rules:
- apiGroups:
  - "*"
  resources:
  - '*'
  verbs:
  - get
  - list
